class AppStrings {
  static const Map<String, Map<String, String>> dict = {
    'settings': {'zh': '设置', 'en': 'Settings'},
    'basic_settings': {'zh': '基础设置', 'en': 'Basic Settings'},
    'notifications': {'zh': '提醒设置', 'en': 'Notifications'},
    'data_storage': {'zh': '高级与数据管理', 'en': 'Data & Storage'},
    'language': {'zh': '语言 / Language', 'en': 'Language / 语言'},
    'semester_start_date': {
      'zh': '第一周开始日期',
      'en': 'First Week Start Date',
    },
    'semester_total_weeks': {'zh': '学期总周数', 'en': 'Total Semester Weeks'},
    'schedule_time_settings': {
      'zh': '作息时间与节次设置',
      'en': 'Class Time & Period Settings',
    },
    'schedule_time_settings_subtitle': {
      'zh': '编辑每天的上课节次和时间段',
      'en': 'Edit daily class periods and time ranges',
    },
    'reminder_time': {'zh': '课前提醒时间', 'en': 'Reminder Advance Time'},
    'clear_browser_cache': {'zh': '清除浏览器缓存', 'en': 'Clear Browser Cache'},
    'clear_browser_cache_subtitle': {
      'zh': '解决教务系统登录失效',
      'en': 'Fix expired academic system login',
    },
    'clear_all_local_data': {'zh': '清除所有本地数据', 'en': 'Clear All Local Data'},
    'clear_all_local_data_subtitle': {
      'zh': '清空课程和日程，操作不可恢复',
      'en': 'Delete all courses and events permanently',
    },
    'weeks_suffix': {'zh': '周', 'en': 'weeks'},
    'minutes_suffix': {'zh': '分钟', 'en': 'min'},
    'cache_cleared': {
      'zh': '缓存已清除，下次导入需重新登录',
      'en': 'Cache cleared. Login again next time you import.',
    },
    'confirm_clear': {'zh': '确认清空', 'en': 'Confirm Clear'},
    'confirm_clear_message': {
      'zh': '确定要清空所有本地课程和日程数据吗？此操作不可逆。',
      'en': 'Clear all local courses and events? This action cannot be undone.',
    },
    'cancel': {'zh': '取消', 'en': 'Cancel'},
    'confirm': {'zh': '确认', 'en': 'Confirm'},
    'all_local_data_cleared': {
      'zh': '本地课程与日程数据已清空',
      'en': 'Local courses and events have been cleared.',
    },
    'chinese': {'zh': '中文', 'en': 'Chinese'},
    'english': {'zh': 'English', 'en': 'English'},
    'advance_prefix': {'zh': '提前', 'en': 'Before'},
    'timetable': {'zh': '课表', 'en': 'Timetable'},
    'day_view': {'zh': '日视图', 'en': 'Day View'},
    'week_view': {'zh': '周视图', 'en': 'Week View'},
    'import_from_system': {
      'zh': '导入教务课表',
      'en': 'Import from Academic System',
    },
    'today': {'zh': '回到今日', 'en': 'Today'},
    'add_course': {'zh': '添加课程', 'en': 'Add Course'},
    'jump_to_week': {'zh': '跳转周次', 'en': 'Jump to Week'},
    'week_prefix': {'zh': '第 ', 'en': 'Week '},
    'week_suffix': {'zh': ' 周', 'en': ''},
    'week_label_format': {'zh': '第 {week} 周', 'en': 'Week {week}'},
    'period_range_format': {
      'zh': '第 {start}-{end} 节',
      'en': 'Period {start}-{end}',
    },
    'no_courses_today': {'zh': '今天没有课程。', 'en': 'No courses today.'},
    'no_courses_for_day': {
      'zh': '本周这一天没有课程或日程。',
      'en': 'No courses or events for this day in this week.',
    },
    'teacher': {'zh': '教师', 'en': 'Teacher'},
    'location': {'zh': '地点', 'en': 'Location'},
    'periods': {'zh': '节次', 'en': 'Periods'},
    'time': {'zh': '时间', 'en': 'Time'},
    'weekday': {'zh': '星期', 'en': 'Weekday'},
    'weeks': {'zh': '周次', 'en': 'Weeks'},
    'edit_course': {'zh': '编辑课程', 'en': 'Edit Course'},
    'delete_course': {'zh': '删除课程', 'en': 'Delete Course'},
    'alarm': {'zh': '提醒', 'en': 'Alarm'},
    'enabled': {'zh': '开启', 'en': 'Enabled'},
    'disabled': {'zh': '关闭', 'en': 'Disabled'},
    'delete_event': {'zh': '删除日程', 'en': 'Delete Event'},
    'location_pending': {'zh': '地点待定', 'en': 'Location pending'},
    'not_set': {'zh': '未设置', 'en': 'Not set'},
    'add_schedule': {'zh': '添加日程', 'en': 'Add Schedule'},
    'add_event': {'zh': '添加日程', 'en': 'Add Event'},
    'save': {'zh': '保存', 'en': 'Save'},
    'saving': {'zh': '保存中...', 'en': 'Saving...'},
    'save_changes': {'zh': '保存修改', 'en': 'Save Changes'},
    'course_name': {'zh': '课程名称', 'en': 'Course Name'},
    'event_name': {'zh': '日程名称', 'en': 'Event Name'},
    'weekday_label': {'zh': '星期几', 'en': 'Weekday'},
    'teaching_weeks': {'zh': '上课周次', 'en': 'Teaching Weeks'},
    'start_period': {'zh': '开始节次', 'en': 'Start Period'},
    'end_period': {'zh': '结束节次', 'en': 'End Period'},
    'card_color': {'zh': '卡片颜色', 'en': 'Card Color'},
    'date_time': {'zh': '日期与时间', 'en': 'Date & Time'},
    'date': {'zh': '日期', 'en': 'Date'},
    'select_event_time': {'zh': '请选择日程时间', 'en': 'Select the event time'},
    'select_date': {'zh': '请选择日期', 'en': 'Select date'},
    'select_time': {'zh': '请选择时间', 'en': 'Select time'},
    'enable_alarm_reminder': {'zh': '开启提醒', 'en': 'Enable Alarm Reminder'},
    'course_updated': {'zh': '课程已更新', 'en': 'Course updated'},
    'course_added': {'zh': '课程已添加', 'en': 'Course added'},
    'event_added': {'zh': '日程已添加', 'en': 'Event added'},
    'please_enter_course_name': {
      'zh': '请输入课程名称',
      'en': 'Please enter a course name',
    },
    'please_enter_location': {
      'zh': '请输入地点',
      'en': 'Please enter a location',
    },
    'please_enter_event_name': {
      'zh': '请输入日程名称',
      'en': 'Please enter an event name',
    },
    'please_select_teaching_week': {
      'zh': '请至少选择一个上课周次',
      'en': 'Please select at least one teaching week',
    },
    'configure_periods_first': {
      'zh': '请先在设置中配置上课节次',
      'en': 'Please configure class periods in Settings first',
    },
    'selected_periods_out_of_range': {
      'zh': '所选节次超出范围',
      'en': 'Selected periods are out of range',
    },
    'end_period_invalid': {
      'zh': '结束节次必须大于或等于开始节次',
      'en': 'End period must be greater than or equal to start period',
    },
    'please_select_date_time': {
      'zh': '请选择日期和时间',
      'en': 'Please select a date and time',
    },
    'timeline_density': {'zh': '时间轴密度', 'en': 'Timeline Density'},
    'class_duration': {'zh': '单节时长', 'en': 'Class Duration'},
    'short_break': {'zh': '小课间', 'en': 'Short Break'},
    'big_break': {'zh': '大课间', 'en': 'Big Break'},
    'morning': {'zh': '上午', 'en': 'Morning'},
    'afternoon': {'zh': '下午', 'en': 'Afternoon'},
    'evening': {'zh': '晚上', 'en': 'Evening'},
    'session_start': {'zh': '开始时间', 'en': 'Start Time'},
    'session_classes': {'zh': '节次数量', 'en': 'Class Count'},
    'period_count': {'zh': '节', 'en': 'period(s)'},
    'monday': {'zh': '周一', 'en': 'Monday'},
    'tuesday': {'zh': '周二', 'en': 'Tuesday'},
    'wednesday': {'zh': '周三', 'en': 'Wednesday'},
    'thursday': {'zh': '周四', 'en': 'Thursday'},
    'friday': {'zh': '周五', 'en': 'Friday'},
    'saturday': {'zh': '周六', 'en': 'Saturday'},
    'sunday': {'zh': '周日', 'en': 'Sunday'},
    'mon_short': {'zh': '周一', 'en': 'Mon'},
    'tue_short': {'zh': '周二', 'en': 'Tue'},
    'wed_short': {'zh': '周三', 'en': 'Wed'},
    'thu_short': {'zh': '周四', 'en': 'Thu'},
    'fri_short': {'zh': '周五', 'en': 'Fri'},
    'sat_short': {'zh': '周六', 'en': 'Sat'},
    'sun_short': {'zh': '周日', 'en': 'Sun'},
    'event_marker': {'zh': '📌', 'en': '📌'},
    'academic_import': {'zh': '教务课表导入', 'en': 'Academic Timetable Import'},
    'extract_timetable': {'zh': '一键提取课表', 'en': 'Extract Timetable'},
    'extracting': {'zh': '正在提取...', 'en': 'Extracting...'},
    'import_success': {'zh': '成功导入课程', 'en': 'Successfully imported courses'},
  };

  static String get(String key, String languageCode) {
    return dict[key]?[languageCode] ?? dict[key]?['zh'] ?? key;
  }
}
